# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import droid_msg_pb2 as droid__msg__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in arm_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ArmServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetArmConfig = channel.unary_unary(
                '/droidgrpc.ArmService/GetArmConfig',
                request_serializer=droid__msg__pb2.Empty.SerializeToString,
                response_deserializer=droid__msg__pb2.DroidConfigs.FromString,
                _registered_method=True)
        self.GetArmState = channel.unary_unary(
                '/droidgrpc.ArmService/GetArmState',
                request_serializer=droid__msg__pb2.Empty.SerializeToString,
                response_deserializer=droid__msg__pb2.DroidArmResponse.FromString,
                _registered_method=True)
        self.GetArmStateStream = channel.unary_stream(
                '/droidgrpc.ArmService/GetArmStateStream',
                request_serializer=droid__msg__pb2.Empty.SerializeToString,
                response_deserializer=droid__msg__pb2.DroidArmResponse.FromString,
                _registered_method=True)
        self.SetArmCommand = channel.unary_unary(
                '/droidgrpc.ArmService/SetArmCommand',
                request_serializer=droid__msg__pb2.DroidCommandRequest.SerializeToString,
                response_deserializer=droid__msg__pb2.Empty.FromString,
                _registered_method=True)
        self.SetArmCommandStream = channel.stream_unary(
                '/droidgrpc.ArmService/SetArmCommandStream',
                request_serializer=droid__msg__pb2.DroidCommandRequest.SerializeToString,
                response_deserializer=droid__msg__pb2.Empty.FromString,
                _registered_method=True)
        self.ExchangeArmControlStream = channel.stream_stream(
                '/droidgrpc.ArmService/ExchangeArmControlStream',
                request_serializer=droid__msg__pb2.DroidCommandRequest.SerializeToString,
                response_deserializer=droid__msg__pb2.DroidArmResponse.FromString,
                _registered_method=True)


class ArmServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetArmConfig(self, request, context):
        """Get robot config information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArmState(self, request, context):
        """Get robot state information (such as kinematic state, power state, or faults).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArmStateStream(self, request, context):
        """Lightweight Streaming version of RobotState
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetArmCommand(self, request, context):
        """Command updates for joint control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetArmCommandStream(self, request_iterator, context):
        """Command updates for joint control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeArmControlStream(self, request_iterator, context):
        """Robot State and Command updates for robot control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetArmConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArmConfig,
                    request_deserializer=droid__msg__pb2.Empty.FromString,
                    response_serializer=droid__msg__pb2.DroidConfigs.SerializeToString,
            ),
            'GetArmState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArmState,
                    request_deserializer=droid__msg__pb2.Empty.FromString,
                    response_serializer=droid__msg__pb2.DroidArmResponse.SerializeToString,
            ),
            'GetArmStateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetArmStateStream,
                    request_deserializer=droid__msg__pb2.Empty.FromString,
                    response_serializer=droid__msg__pb2.DroidArmResponse.SerializeToString,
            ),
            'SetArmCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SetArmCommand,
                    request_deserializer=droid__msg__pb2.DroidCommandRequest.FromString,
                    response_serializer=droid__msg__pb2.Empty.SerializeToString,
            ),
            'SetArmCommandStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SetArmCommandStream,
                    request_deserializer=droid__msg__pb2.DroidCommandRequest.FromString,
                    response_serializer=droid__msg__pb2.Empty.SerializeToString,
            ),
            'ExchangeArmControlStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ExchangeArmControlStream,
                    request_deserializer=droid__msg__pb2.DroidCommandRequest.FromString,
                    response_serializer=droid__msg__pb2.DroidArmResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'droidgrpc.ArmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('droidgrpc.ArmService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArmService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetArmConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droidgrpc.ArmService/GetArmConfig',
            droid__msg__pb2.Empty.SerializeToString,
            droid__msg__pb2.DroidConfigs.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArmState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droidgrpc.ArmService/GetArmState',
            droid__msg__pb2.Empty.SerializeToString,
            droid__msg__pb2.DroidArmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArmStateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/droidgrpc.ArmService/GetArmStateStream',
            droid__msg__pb2.Empty.SerializeToString,
            droid__msg__pb2.DroidArmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetArmCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droidgrpc.ArmService/SetArmCommand',
            droid__msg__pb2.DroidCommandRequest.SerializeToString,
            droid__msg__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetArmCommandStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/droidgrpc.ArmService/SetArmCommandStream',
            droid__msg__pb2.DroidCommandRequest.SerializeToString,
            droid__msg__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeArmControlStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/droidgrpc.ArmService/ExchangeArmControlStream',
            droid__msg__pb2.DroidCommandRequest.SerializeToString,
            droid__msg__pb2.DroidArmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
