"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
motion_control.proto"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Empty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Empty = Empty

@typing.final
class DroidConfigs(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOINT_NAME_FIELD_NUMBER: builtins.int
    PZERO_FIELD_NUMBER: builtins.int
    PMIN_FIELD_NUMBER: builtins.int
    PMAX_FIELD_NUMBER: builtins.int
    IMAX_FIELD_NUMBER: builtins.int
    KP_FIELD_NUMBER: builtins.int
    KD_FIELD_NUMBER: builtins.int
    @property
    def joint_name(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def pzero(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """关节零点偏移   /* degree 或 mm */"""

    @property
    def pmin(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """关节最小限幅"""

    @property
    def pmax(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """关节最大限幅"""

    @property
    def imax(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def kp(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def kd(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        joint_name: collections.abc.Iterable[builtins.str] | None = ...,
        pzero: collections.abc.Iterable[builtins.float] | None = ...,
        pmin: collections.abc.Iterable[builtins.float] | None = ...,
        pmax: collections.abc.Iterable[builtins.float] | None = ...,
        imax: collections.abc.Iterable[builtins.float] | None = ...,
        kp: collections.abc.Iterable[builtins.float] | None = ...,
        kd: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["imax", b"imax", "joint_name", b"joint_name", "kd", b"kd", "kp", b"kp", "pmax", b"pmax", "pmin", b"pmin", "pzero", b"pzero"]) -> None: ...

global___DroidConfigs = DroidConfigs

@typing.final
class DroidStateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYSTEM_TIC_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    VELOCITY_FIELD_NUMBER: builtins.int
    TORQUE_FIELD_NUMBER: builtins.int
    TEMPERATURE_FIELD_NUMBER: builtins.int
    ABS_ENCODER_FIELD_NUMBER: builtins.int
    PACK_LOSS_FIELD_NUMBER: builtins.int
    LOWLEVEL_INIT_FIELD_NUMBER: builtins.int
    IMU_ACC_FIELD_NUMBER: builtins.int
    IMU_EULER_FIELD_NUMBER: builtins.int
    IMU_GYRO_FIELD_NUMBER: builtins.int
    EST_EULER_FIELD_NUMBER: builtins.int
    EST_COM_POS_FIELD_NUMBER: builtins.int
    EST_COM_VEL_FIELD_NUMBER: builtins.int
    FOOT_FORCE_FIELD_NUMBER: builtins.int
    IMU_STAMP_FIELD_NUMBER: builtins.int
    BUS_VOLTAGE_FIELD_NUMBER: builtins.int
    BUS_CURRENT_FIELD_NUMBER: builtins.int
    BUS_ENERGY_FIELD_NUMBER: builtins.int
    RC_DU_FIELD_NUMBER: builtins.int
    RC_KEYS_FIELD_NUMBER: builtins.int
    system_tic: builtins.int
    lowlevel_init: builtins.int
    imu_stamp: builtins.int
    bus_voltage: builtins.float
    bus_current: builtins.float
    bus_energy: builtins.float
    @property
    def position(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def velocity(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def torque(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def temperature(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def abs_encoder(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def pack_loss(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def imu_acc(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def imu_euler(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def imu_gyro(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def est_euler(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def est_com_pos(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def est_com_vel(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def foot_force(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def rc_du(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def rc_keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        system_tic: builtins.int = ...,
        position: collections.abc.Iterable[builtins.float] | None = ...,
        velocity: collections.abc.Iterable[builtins.float] | None = ...,
        torque: collections.abc.Iterable[builtins.float] | None = ...,
        temperature: collections.abc.Iterable[builtins.float] | None = ...,
        abs_encoder: collections.abc.Iterable[builtins.float] | None = ...,
        pack_loss: collections.abc.Iterable[builtins.int] | None = ...,
        lowlevel_init: builtins.int = ...,
        imu_acc: collections.abc.Iterable[builtins.float] | None = ...,
        imu_euler: collections.abc.Iterable[builtins.float] | None = ...,
        imu_gyro: collections.abc.Iterable[builtins.float] | None = ...,
        est_euler: collections.abc.Iterable[builtins.float] | None = ...,
        est_com_pos: collections.abc.Iterable[builtins.float] | None = ...,
        est_com_vel: collections.abc.Iterable[builtins.float] | None = ...,
        foot_force: collections.abc.Iterable[builtins.float] | None = ...,
        imu_stamp: builtins.int = ...,
        bus_voltage: builtins.float = ...,
        bus_current: builtins.float = ...,
        bus_energy: builtins.float = ...,
        rc_du: collections.abc.Iterable[builtins.float] | None = ...,
        rc_keys: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["abs_encoder", b"abs_encoder", "bus_current", b"bus_current", "bus_energy", b"bus_energy", "bus_voltage", b"bus_voltage", "est_com_pos", b"est_com_pos", "est_com_vel", b"est_com_vel", "est_euler", b"est_euler", "foot_force", b"foot_force", "imu_acc", b"imu_acc", "imu_euler", b"imu_euler", "imu_gyro", b"imu_gyro", "imu_stamp", b"imu_stamp", "lowlevel_init", b"lowlevel_init", "pack_loss", b"pack_loss", "position", b"position", "rc_du", b"rc_du", "rc_keys", b"rc_keys", "system_tic", b"system_tic", "temperature", b"temperature", "torque", b"torque", "velocity", b"velocity"]) -> None: ...

global___DroidStateResponse = DroidStateResponse

@typing.final
class DroidArmResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYSTEM_TIC_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    VELOCITY_FIELD_NUMBER: builtins.int
    TORQUE_FIELD_NUMBER: builtins.int
    TEMPERATURE_FIELD_NUMBER: builtins.int
    ABS_ENCODER_FIELD_NUMBER: builtins.int
    PACK_LOSS_FIELD_NUMBER: builtins.int
    LOWLEVEL_INIT_FIELD_NUMBER: builtins.int
    system_tic: builtins.int
    lowlevel_init: builtins.int
    @property
    def position(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def velocity(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def torque(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def temperature(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def abs_encoder(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def pack_loss(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        system_tic: builtins.int = ...,
        position: collections.abc.Iterable[builtins.float] | None = ...,
        velocity: collections.abc.Iterable[builtins.float] | None = ...,
        torque: collections.abc.Iterable[builtins.float] | None = ...,
        temperature: collections.abc.Iterable[builtins.float] | None = ...,
        abs_encoder: collections.abc.Iterable[builtins.float] | None = ...,
        pack_loss: collections.abc.Iterable[builtins.int] | None = ...,
        lowlevel_init: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["abs_encoder", b"abs_encoder", "lowlevel_init", b"lowlevel_init", "pack_loss", b"pack_loss", "position", b"position", "system_tic", b"system_tic", "temperature", b"temperature", "torque", b"torque", "velocity", b"velocity"]) -> None: ...

global___DroidArmResponse = DroidArmResponse

@typing.final
class DroidCommandRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODE_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    VELOCITY_FIELD_NUMBER: builtins.int
    TORQUE_FIELD_NUMBER: builtins.int
    CMD_ENABLE_FIELD_NUMBER: builtins.int
    ENS_FIELD_NUMBER: builtins.int
    KP_FIELD_NUMBER: builtins.int
    KD_FIELD_NUMBER: builtins.int
    MAX_TORQUE_FIELD_NUMBER: builtins.int
    FINGER_FIELD_NUMBER: builtins.int
    cmd_enable: builtins.int
    @property
    def mode(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def position(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def velocity(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def torque(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def ens(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def kp(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def kd(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def max_torque(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def finger(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        mode: collections.abc.Iterable[builtins.int] | None = ...,
        position: collections.abc.Iterable[builtins.float] | None = ...,
        velocity: collections.abc.Iterable[builtins.float] | None = ...,
        torque: collections.abc.Iterable[builtins.float] | None = ...,
        cmd_enable: builtins.int = ...,
        ens: collections.abc.Iterable[builtins.int] | None = ...,
        kp: collections.abc.Iterable[builtins.float] | None = ...,
        kd: collections.abc.Iterable[builtins.float] | None = ...,
        max_torque: collections.abc.Iterable[builtins.float] | None = ...,
        finger: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cmd_enable", b"cmd_enable", "ens", b"ens", "finger", b"finger", "kd", b"kd", "kp", b"kp", "max_torque", b"max_torque", "mode", b"mode", "position", b"position", "torque", b"torque", "velocity", b"velocity"]) -> None: ...

global___DroidCommandRequest = DroidCommandRequest
