"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Empty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Empty = Empty

@typing.final
class HeadArkitMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVO_JSON_FIELD_NUMBER: builtins.int
    servo_json: builtins.str
    def __init__(
        self,
        *,
        servo_json: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["servo_json", b"servo_json"]) -> None: ...

global___HeadArkitMessage = HeadArkitMessage
