# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: leg_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import droid_msg_pb2 as droid__msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11leg_service.proto\x12\tdroidgrpc\x1a\x0f\x64roid_msg.proto2\xc6\x03\n\nLegService\x12\x39\n\x0cGetLegConfig\x12\x10.droidgrpc.Empty\x1a\x17.droidgrpc.DroidConfigs\x12@\n\x0bGetLegState\x12\x10.droidgrpc.Empty\x1a\x1d.droidgrpc.DroidStateResponse\"\x00\x12H\n\x11GetLegStateStream\x12\x10.droidgrpc.Empty\x1a\x1d.droidgrpc.DroidStateResponse\"\x00\x30\x01\x12\x43\n\rSetLegCommand\x12\x1e.droidgrpc.DroidCommandRequest\x1a\x10.droidgrpc.Empty\"\x00\x12K\n\x13SetLegCommandStream\x12\x1e.droidgrpc.DroidCommandRequest\x1a\x10.droidgrpc.Empty\"\x00(\x01\x12_\n\x18\x45xchangeLegControlStream\x12\x1e.droidgrpc.DroidCommandRequest\x1a\x1d.droidgrpc.DroidStateResponse\"\x00(\x01\x30\x01\x42\x11\x42\x0fLegServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'leg_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\017LegServiceProto'
  _globals['_LEGSERVICE']._serialized_start=50
  _globals['_LEGSERVICE']._serialized_end=504
# @@protoc_insertion_point(module_scope)
