# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import droid_msg_pb2 as droid__msg__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in leg_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class LegServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLegConfig = channel.unary_unary(
                '/droidgrpc.LegService/GetLegConfig',
                request_serializer=droid__msg__pb2.Empty.SerializeToString,
                response_deserializer=droid__msg__pb2.DroidConfigs.FromString,
                _registered_method=True)
        self.GetLegState = channel.unary_unary(
                '/droidgrpc.LegService/GetLegState',
                request_serializer=droid__msg__pb2.Empty.SerializeToString,
                response_deserializer=droid__msg__pb2.DroidStateResponse.FromString,
                _registered_method=True)
        self.GetLegStateStream = channel.unary_stream(
                '/droidgrpc.LegService/GetLegStateStream',
                request_serializer=droid__msg__pb2.Empty.SerializeToString,
                response_deserializer=droid__msg__pb2.DroidStateResponse.FromString,
                _registered_method=True)
        self.SetLegCommand = channel.unary_unary(
                '/droidgrpc.LegService/SetLegCommand',
                request_serializer=droid__msg__pb2.DroidCommandRequest.SerializeToString,
                response_deserializer=droid__msg__pb2.Empty.FromString,
                _registered_method=True)
        self.SetLegCommandStream = channel.stream_unary(
                '/droidgrpc.LegService/SetLegCommandStream',
                request_serializer=droid__msg__pb2.DroidCommandRequest.SerializeToString,
                response_deserializer=droid__msg__pb2.Empty.FromString,
                _registered_method=True)
        self.ExchangeLegControlStream = channel.stream_stream(
                '/droidgrpc.LegService/ExchangeLegControlStream',
                request_serializer=droid__msg__pb2.DroidCommandRequest.SerializeToString,
                response_deserializer=droid__msg__pb2.DroidStateResponse.FromString,
                _registered_method=True)


class LegServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLegConfig(self, request, context):
        """Get robot config information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLegState(self, request, context):
        """Get robot state information (such as kinematic state, power state, or faults).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLegStateStream(self, request, context):
        """Lightweight Streaming version of RobotState
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLegCommand(self, request, context):
        """Command updates for joint control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLegCommandStream(self, request_iterator, context):
        """Command updates for joint control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeLegControlStream(self, request_iterator, context):
        """Robot State and Command updates for robot control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LegServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLegConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLegConfig,
                    request_deserializer=droid__msg__pb2.Empty.FromString,
                    response_serializer=droid__msg__pb2.DroidConfigs.SerializeToString,
            ),
            'GetLegState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLegState,
                    request_deserializer=droid__msg__pb2.Empty.FromString,
                    response_serializer=droid__msg__pb2.DroidStateResponse.SerializeToString,
            ),
            'GetLegStateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetLegStateStream,
                    request_deserializer=droid__msg__pb2.Empty.FromString,
                    response_serializer=droid__msg__pb2.DroidStateResponse.SerializeToString,
            ),
            'SetLegCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLegCommand,
                    request_deserializer=droid__msg__pb2.DroidCommandRequest.FromString,
                    response_serializer=droid__msg__pb2.Empty.SerializeToString,
            ),
            'SetLegCommandStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SetLegCommandStream,
                    request_deserializer=droid__msg__pb2.DroidCommandRequest.FromString,
                    response_serializer=droid__msg__pb2.Empty.SerializeToString,
            ),
            'ExchangeLegControlStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ExchangeLegControlStream,
                    request_deserializer=droid__msg__pb2.DroidCommandRequest.FromString,
                    response_serializer=droid__msg__pb2.DroidStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'droidgrpc.LegService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('droidgrpc.LegService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LegService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLegConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droidgrpc.LegService/GetLegConfig',
            droid__msg__pb2.Empty.SerializeToString,
            droid__msg__pb2.DroidConfigs.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLegState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droidgrpc.LegService/GetLegState',
            droid__msg__pb2.Empty.SerializeToString,
            droid__msg__pb2.DroidStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLegStateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/droidgrpc.LegService/GetLegStateStream',
            droid__msg__pb2.Empty.SerializeToString,
            droid__msg__pb2.DroidStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLegCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droidgrpc.LegService/SetLegCommand',
            droid__msg__pb2.DroidCommandRequest.SerializeToString,
            droid__msg__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLegCommandStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/droidgrpc.LegService/SetLegCommandStream',
            droid__msg__pb2.DroidCommandRequest.SerializeToString,
            droid__msg__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeLegControlStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/droidgrpc.LegService/ExchangeLegControlStream',
            droid__msg__pb2.DroidCommandRequest.SerializeToString,
            droid__msg__pb2.DroidStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
