"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) 2024 Droid Robot, Inc.  All rights reserved.

Downloading, reproducing, distributing or otherwise using the SDK Software
is subject to the terms and conditions of the Droid Robot Software
Development Kit License (20240808-DRSDK-SL).
"""
import abc
import collections.abc
import droid_msg_pb2
import grpc
import grpc.aio
import typing

_T = typing.TypeVar('_T')

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta):
    ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore
    ...

class LegServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    GetLegConfig: grpc.UnaryUnaryMultiCallable[
        droid_msg_pb2.Empty,
        droid_msg_pb2.DroidConfigs,
    ]
    """Get robot config information"""
    GetLegState: grpc.UnaryUnaryMultiCallable[
        droid_msg_pb2.Empty,
        droid_msg_pb2.DroidStateResponse,
    ]
    """Get robot state information (such as kinematic state, power state, or faults)."""
    GetLegStateStream: grpc.UnaryStreamMultiCallable[
        droid_msg_pb2.Empty,
        droid_msg_pb2.DroidStateResponse,
    ]
    """Lightweight Streaming version of RobotState"""
    SetLegCommand: grpc.UnaryUnaryMultiCallable[
        droid_msg_pb2.DroidCommandRequest,
        droid_msg_pb2.Empty,
    ]
    """Command updates for joint control"""
    SetLegCommandStream: grpc.StreamUnaryMultiCallable[
        droid_msg_pb2.DroidCommandRequest,
        droid_msg_pb2.Empty,
    ]
    """Command updates for joint control"""
    ExchangeLegControlStream: grpc.StreamStreamMultiCallable[
        droid_msg_pb2.DroidCommandRequest,
        droid_msg_pb2.DroidStateResponse,
    ]
    """Robot State and Command updates for robot control"""

class LegServiceAsyncStub:
    GetLegConfig: grpc.aio.UnaryUnaryMultiCallable[
        droid_msg_pb2.Empty,
        droid_msg_pb2.DroidConfigs,
    ]
    """Get robot config information"""
    GetLegState: grpc.aio.UnaryUnaryMultiCallable[
        droid_msg_pb2.Empty,
        droid_msg_pb2.DroidStateResponse,
    ]
    """Get robot state information (such as kinematic state, power state, or faults)."""
    GetLegStateStream: grpc.aio.UnaryStreamMultiCallable[
        droid_msg_pb2.Empty,
        droid_msg_pb2.DroidStateResponse,
    ]
    """Lightweight Streaming version of RobotState"""
    SetLegCommand: grpc.aio.UnaryUnaryMultiCallable[
        droid_msg_pb2.DroidCommandRequest,
        droid_msg_pb2.Empty,
    ]
    """Command updates for joint control"""
    SetLegCommandStream: grpc.aio.StreamUnaryMultiCallable[
        droid_msg_pb2.DroidCommandRequest,
        droid_msg_pb2.Empty,
    ]
    """Command updates for joint control"""
    ExchangeLegControlStream: grpc.aio.StreamStreamMultiCallable[
        droid_msg_pb2.DroidCommandRequest,
        droid_msg_pb2.DroidStateResponse,
    ]
    """Robot State and Command updates for robot control"""

class LegServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def GetLegConfig(
        self,
        request: droid_msg_pb2.Empty,
        context: _ServicerContext,
    ) -> typing.Union[droid_msg_pb2.DroidConfigs, collections.abc.Awaitable[droid_msg_pb2.DroidConfigs]]:
        """Get robot config information"""
    @abc.abstractmethod
    def GetLegState(
        self,
        request: droid_msg_pb2.Empty,
        context: _ServicerContext,
    ) -> typing.Union[droid_msg_pb2.DroidStateResponse, collections.abc.Awaitable[droid_msg_pb2.DroidStateResponse]]:
        """Get robot state information (such as kinematic state, power state, or faults)."""
    @abc.abstractmethod
    def GetLegStateStream(
        self,
        request: droid_msg_pb2.Empty,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[droid_msg_pb2.DroidStateResponse], collections.abc.AsyncIterator[droid_msg_pb2.DroidStateResponse]]:
        """Lightweight Streaming version of RobotState"""
    @abc.abstractmethod
    def SetLegCommand(
        self,
        request: droid_msg_pb2.DroidCommandRequest,
        context: _ServicerContext,
    ) -> typing.Union[droid_msg_pb2.Empty, collections.abc.Awaitable[droid_msg_pb2.Empty]]:
        """Command updates for joint control"""
    @abc.abstractmethod
    def SetLegCommandStream(
        self,
        request_iterator: _MaybeAsyncIterator[droid_msg_pb2.DroidCommandRequest],
        context: _ServicerContext,
    ) -> typing.Union[droid_msg_pb2.Empty, collections.abc.Awaitable[droid_msg_pb2.Empty]]:
        """Command updates for joint control"""
    @abc.abstractmethod
    def ExchangeLegControlStream(
        self,
        request_iterator: _MaybeAsyncIterator[droid_msg_pb2.DroidCommandRequest],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[droid_msg_pb2.DroidStateResponse], collections.abc.AsyncIterator[droid_msg_pb2.DroidStateResponse]]:
        """Robot State and Command updates for robot control"""

def add_LegServiceServicer_to_server(servicer: LegServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
