"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import collections.abc
import grpc
import grpc.aio
import mobilebase_pb2
import typing

_T = typing.TypeVar('_T')

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta):
    ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore
    ...

class MobileBaseServiceStub:
    """移动底盘服务定义"""

    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Move: grpc.UnaryUnaryMultiCallable[
        mobilebase_pb2.MoveRequest,
        mobilebase_pb2.MoveResponse,
    ]
    """基本运动控制"""
    Stop: grpc.UnaryUnaryMultiCallable[
        mobilebase_pb2.StopRequest,
        mobilebase_pb2.StopResponse,
    ]
    """停止移动"""
    GetStatus: grpc.UnaryUnaryMultiCallable[
        mobilebase_pb2.StatusRequest,
        mobilebase_pb2.StatusResponse,
    ]
    """获取底盘状态"""
    MoveToTarget: grpc.UnaryUnaryMultiCallable[
        mobilebase_pb2.MoveToTargetRequest,
        mobilebase_pb2.MoveToTargetResponse,
    ]
    """移动到指定目标点位"""

class MobileBaseServiceAsyncStub:
    """移动底盘服务定义"""

    Move: grpc.aio.UnaryUnaryMultiCallable[
        mobilebase_pb2.MoveRequest,
        mobilebase_pb2.MoveResponse,
    ]
    """基本运动控制"""
    Stop: grpc.aio.UnaryUnaryMultiCallable[
        mobilebase_pb2.StopRequest,
        mobilebase_pb2.StopResponse,
    ]
    """停止移动"""
    GetStatus: grpc.aio.UnaryUnaryMultiCallable[
        mobilebase_pb2.StatusRequest,
        mobilebase_pb2.StatusResponse,
    ]
    """获取底盘状态"""
    MoveToTarget: grpc.aio.UnaryUnaryMultiCallable[
        mobilebase_pb2.MoveToTargetRequest,
        mobilebase_pb2.MoveToTargetResponse,
    ]
    """移动到指定目标点位"""

class MobileBaseServiceServicer(metaclass=abc.ABCMeta):
    """移动底盘服务定义"""

    @abc.abstractmethod
    def Move(
        self,
        request: mobilebase_pb2.MoveRequest,
        context: _ServicerContext,
    ) -> typing.Union[mobilebase_pb2.MoveResponse, collections.abc.Awaitable[mobilebase_pb2.MoveResponse]]:
        """基本运动控制"""
    @abc.abstractmethod
    def Stop(
        self,
        request: mobilebase_pb2.StopRequest,
        context: _ServicerContext,
    ) -> typing.Union[mobilebase_pb2.StopResponse, collections.abc.Awaitable[mobilebase_pb2.StopResponse]]:
        """停止移动"""
    @abc.abstractmethod
    def GetStatus(
        self,
        request: mobilebase_pb2.StatusRequest,
        context: _ServicerContext,
    ) -> typing.Union[mobilebase_pb2.StatusResponse, collections.abc.Awaitable[mobilebase_pb2.StatusResponse]]:
        """获取底盘状态"""
    @abc.abstractmethod
    def MoveToTarget(
        self,
        request: mobilebase_pb2.MoveToTargetRequest,
        context: _ServicerContext,
    ) -> typing.Union[mobilebase_pb2.MoveToTargetResponse, collections.abc.Awaitable[mobilebase_pb2.MoveToTargetResponse]]:
        """移动到指定目标点位"""

def add_MobileBaseServiceServicer_to_server(servicer: MobileBaseServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
