# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mobilebase_pb2 as mobilebase__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mobilebase_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class MobileBaseServiceStub(object):
    """移动底盘服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Move = channel.unary_unary(
                '/mobilebase.MobileBaseService/Move',
                request_serializer=mobilebase__pb2.MoveRequest.SerializeToString,
                response_deserializer=mobilebase__pb2.MoveResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/mobilebase.MobileBaseService/Stop',
                request_serializer=mobilebase__pb2.StopRequest.SerializeToString,
                response_deserializer=mobilebase__pb2.StopResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/mobilebase.MobileBaseService/GetStatus',
                request_serializer=mobilebase__pb2.StatusRequest.SerializeToString,
                response_deserializer=mobilebase__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.MoveToTarget = channel.unary_unary(
                '/mobilebase.MobileBaseService/MoveToTarget',
                request_serializer=mobilebase__pb2.MoveToTargetRequest.SerializeToString,
                response_deserializer=mobilebase__pb2.MoveToTargetResponse.FromString,
                _registered_method=True)


class MobileBaseServiceServicer(object):
    """移动底盘服务定义
    """

    def Move(self, request, context):
        """基本运动控制
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """停止移动
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """获取底盘状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveToTarget(self, request, context):
        """移动到指定目标点位
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MobileBaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=mobilebase__pb2.MoveRequest.FromString,
                    response_serializer=mobilebase__pb2.MoveResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=mobilebase__pb2.StopRequest.FromString,
                    response_serializer=mobilebase__pb2.StopResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=mobilebase__pb2.StatusRequest.FromString,
                    response_serializer=mobilebase__pb2.StatusResponse.SerializeToString,
            ),
            'MoveToTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveToTarget,
                    request_deserializer=mobilebase__pb2.MoveToTargetRequest.FromString,
                    response_serializer=mobilebase__pb2.MoveToTargetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mobilebase.MobileBaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mobilebase.MobileBaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MobileBaseService(object):
    """移动底盘服务定义
    """

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mobilebase.MobileBaseService/Move',
            mobilebase__pb2.MoveRequest.SerializeToString,
            mobilebase__pb2.MoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mobilebase.MobileBaseService/Stop',
            mobilebase__pb2.StopRequest.SerializeToString,
            mobilebase__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mobilebase.MobileBaseService/GetStatus',
            mobilebase__pb2.StatusRequest.SerializeToString,
            mobilebase__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveToTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mobilebase.MobileBaseService/MoveToTarget',
            mobilebase__pb2.MoveToTargetRequest.SerializeToString,
            mobilebase__pb2.MoveToTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
