# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mobilebase.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10mobilebase.proto\x12\nmobilebase\"\xc5\x01\n\x0bMoveRequest\x12\x17\n\x0flinear_velocity\x18\x01 \x01(\x02\x12\x18\n\x10\x61ngular_velocity\x18\x02 \x01(\x02\x12\x34\n\tdirection\x18\x03 \x01(\x0e\x32!.mobilebase.MoveRequest.Direction\x12\x10\n\x08\x64uration\x18\x04 \x01(\x02\";\n\tDirection\x12\x0b\n\x07\x46ORWARD\x10\x00\x12\x0c\n\x08\x42\x41\x43KWARD\x10\x01\x12\x08\n\x04LEFT\x10\x02\x12\t\n\x05RIGHT\x10\x03\"0\n\x0cMoveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"d\n\x0bStopRequest\x12.\n\x04type\x18\x01 \x01(\x0e\x32 .mobilebase.StopRequest.StopType\"%\n\x08StopType\x12\n\n\x06NORMAL\x10\x00\x12\r\n\tEMERGENCY\x10\x01\"0\n\x0cStopResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0f\n\rStatusRequest\"\xe1\x01\n\x0eStatusResponse\x12/\n\x05state\x18\x01 \x01(\x0e\x32 .mobilebase.StatusResponse.State\x12\x1f\n\x17\x63urrent_linear_velocity\x18\x02 \x01(\x02\x12 \n\x18\x63urrent_angular_velocity\x18\x03 \x01(\x02\x12\x1a\n\x12\x62\x61ttery_percentage\x18\x04 \x01(\x02\x12\x15\n\rerror_message\x18\x05 \x01(\t\"(\n\x05State\x12\x08\n\x04IDLE\x10\x00\x12\n\n\x06MOVING\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"*\n\x13MoveToTargetRequest\x12\x13\n\x0btarget_name\x18\x01 \x01(\t\"8\n\x14MoveToTargetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa8\x02\n\x11MobileBaseService\x12;\n\x04Move\x12\x17.mobilebase.MoveRequest\x1a\x18.mobilebase.MoveResponse\"\x00\x12;\n\x04Stop\x12\x17.mobilebase.StopRequest\x1a\x18.mobilebase.StopResponse\"\x00\x12\x44\n\tGetStatus\x12\x19.mobilebase.StatusRequest\x1a\x1a.mobilebase.StatusResponse\"\x00\x12S\n\x0cMoveToTarget\x12\x1f.mobilebase.MoveToTargetRequest\x1a .mobilebase.MoveToTargetResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mobilebase_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVEREQUEST']._serialized_start=33
  _globals['_MOVEREQUEST']._serialized_end=230
  _globals['_MOVEREQUEST_DIRECTION']._serialized_start=171
  _globals['_MOVEREQUEST_DIRECTION']._serialized_end=230
  _globals['_MOVERESPONSE']._serialized_start=232
  _globals['_MOVERESPONSE']._serialized_end=280
  _globals['_STOPREQUEST']._serialized_start=282
  _globals['_STOPREQUEST']._serialized_end=382
  _globals['_STOPREQUEST_STOPTYPE']._serialized_start=345
  _globals['_STOPREQUEST_STOPTYPE']._serialized_end=382
  _globals['_STOPRESPONSE']._serialized_start=384
  _globals['_STOPRESPONSE']._serialized_end=432
  _globals['_STATUSREQUEST']._serialized_start=434
  _globals['_STATUSREQUEST']._serialized_end=449
  _globals['_STATUSRESPONSE']._serialized_start=452
  _globals['_STATUSRESPONSE']._serialized_end=677
  _globals['_STATUSRESPONSE_STATE']._serialized_start=637
  _globals['_STATUSRESPONSE_STATE']._serialized_end=677
  _globals['_MOVETOTARGETREQUEST']._serialized_start=679
  _globals['_MOVETOTARGETREQUEST']._serialized_end=721
  _globals['_MOVETOTARGETRESPONSE']._serialized_start=723
  _globals['_MOVETOTARGETRESPONSE']._serialized_end=779
  _globals['_MOBILEBASESERVICE']._serialized_start=782
  _globals['_MOBILEBASESERVICE']._serialized_end=1078
# @@protoc_insertion_point(module_scope)
