"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class MoveRequest(google.protobuf.message.Message):
    """移动请求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Direction:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DirectionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[MoveRequest._Direction.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        FORWARD: MoveRequest._Direction.ValueType  # 0
        """前进"""
        BACKWARD: MoveRequest._Direction.ValueType  # 1
        """后退"""
        LEFT: MoveRequest._Direction.ValueType  # 2
        """左转"""
        RIGHT: MoveRequest._Direction.ValueType  # 3
        """右转"""

    class Direction(_Direction, metaclass=_DirectionEnumTypeWrapper):
        """移动方向"""

    FORWARD: MoveRequest.Direction.ValueType  # 0
    """前进"""
    BACKWARD: MoveRequest.Direction.ValueType  # 1
    """后退"""
    LEFT: MoveRequest.Direction.ValueType  # 2
    """左转"""
    RIGHT: MoveRequest.Direction.ValueType  # 3
    """右转"""

    LINEAR_VELOCITY_FIELD_NUMBER: builtins.int
    ANGULAR_VELOCITY_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    linear_velocity: builtins.float
    """线速度 (m/s)"""
    angular_velocity: builtins.float
    """角速度 (rad/s)"""
    direction: global___MoveRequest.Direction.ValueType
    duration: builtins.float
    """移动时间 (秒)，0表示持续移动直到收到停止命令"""
    def __init__(
        self,
        *,
        linear_velocity: builtins.float = ...,
        angular_velocity: builtins.float = ...,
        direction: global___MoveRequest.Direction.ValueType = ...,
        duration: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["angular_velocity", b"angular_velocity", "direction", b"direction", "duration", b"duration", "linear_velocity", b"linear_velocity"]) -> None: ...

global___MoveRequest = MoveRequest

@typing_extensions.final
class MoveResponse(google.protobuf.message.Message):
    """移动响应"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "success", b"success"]) -> None: ...

global___MoveResponse = MoveResponse

@typing_extensions.final
class StopRequest(google.protobuf.message.Message):
    """停止请求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _StopType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StopTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StopRequest._StopType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NORMAL: StopRequest._StopType.ValueType  # 0
        """正常停止"""
        EMERGENCY: StopRequest._StopType.ValueType  # 1
        """紧急停止"""

    class StopType(_StopType, metaclass=_StopTypeEnumTypeWrapper):
        """停止类型"""

    NORMAL: StopRequest.StopType.ValueType  # 0
    """正常停止"""
    EMERGENCY: StopRequest.StopType.ValueType  # 1
    """紧急停止"""

    TYPE_FIELD_NUMBER: builtins.int
    type: global___StopRequest.StopType.ValueType
    def __init__(
        self,
        *,
        type: global___StopRequest.StopType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["type", b"type"]) -> None: ...

global___StopRequest = StopRequest

@typing_extensions.final
class StopResponse(google.protobuf.message.Message):
    """停止响应"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "success", b"success"]) -> None: ...

global___StopResponse = StopResponse

@typing_extensions.final
class StatusRequest(google.protobuf.message.Message):
    """状态请求
    空请求
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___StatusRequest = StatusRequest

@typing_extensions.final
class StatusResponse(google.protobuf.message.Message):
    """状态响应"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _State:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StatusResponse._State.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        IDLE: StatusResponse._State.ValueType  # 0
        """空闲"""
        MOVING: StatusResponse._State.ValueType  # 1
        """移动中"""
        ERROR: StatusResponse._State.ValueType  # 2
        """错误"""

    class State(_State, metaclass=_StateEnumTypeWrapper):
        """当前状态"""

    IDLE: StatusResponse.State.ValueType  # 0
    """空闲"""
    MOVING: StatusResponse.State.ValueType  # 1
    """移动中"""
    ERROR: StatusResponse.State.ValueType  # 2
    """错误"""

    STATE_FIELD_NUMBER: builtins.int
    CURRENT_LINEAR_VELOCITY_FIELD_NUMBER: builtins.int
    CURRENT_ANGULAR_VELOCITY_FIELD_NUMBER: builtins.int
    BATTERY_PERCENTAGE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    state: global___StatusResponse.State.ValueType
    current_linear_velocity: builtins.float
    """当前线速度 (m/s)"""
    current_angular_velocity: builtins.float
    """当前角速度 (rad/s)"""
    battery_percentage: builtins.float
    """电池电量百分比"""
    error_message: builtins.str
    """错误信息（如果有）"""
    def __init__(
        self,
        *,
        state: global___StatusResponse.State.ValueType = ...,
        current_linear_velocity: builtins.float = ...,
        current_angular_velocity: builtins.float = ...,
        battery_percentage: builtins.float = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["battery_percentage", b"battery_percentage", "current_angular_velocity", b"current_angular_velocity", "current_linear_velocity", b"current_linear_velocity", "error_message", b"error_message", "state", b"state"]) -> None: ...

global___StatusResponse = StatusResponse

@typing_extensions.final
class MoveToTargetRequest(google.protobuf.message.Message):
    """移动到目标点位请求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TARGET_NAME_FIELD_NUMBER: builtins.int
    target_name: builtins.str
    """目标点位名称"""
    def __init__(
        self,
        *,
        target_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["target_name", b"target_name"]) -> None: ...

global___MoveToTargetRequest = MoveToTargetRequest

@typing_extensions.final
class MoveToTargetResponse(google.protobuf.message.Message):
    """移动到目标点位响应"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "success", b"success"]) -> None: ...

global___MoveToTargetResponse = MoveToTargetResponse
